In [1]:
import os
import subprocess

import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import *
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import *
from sklearn import model_selection

In [2]:
#citesc setul de date
datasets = pd.read_csv('ObesityDataSet.csv')

In [3]:
#afisez primele 5 
datasets.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no     2   
1  Female  21.0    1.52    56.0                            yes   no     3   
2    Male  23.0    1.80    77.0                            yes   no     2   
3    Male  27.0    1.80    87.0                             no   no     3   
4    Male  22.0    1.78    89.8                             no   no     2   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0    3  Sometimes    no   2.0   no  0.0    1          no   
1    3  Sometimes   yes   3.0  yes  3.0    0   Sometimes   
2    3  Sometimes    no   2.0   no  2.0    1  Frequently   
3    3  Sometimes    no   2.0   no  2.0    0  Frequently   
4    1  Sometimes    no   2.0   no  0.0    0   Sometimes   

                  MTRANS          NObeyesdad  
0  Public_Transportation       Normal_Weight  
1  Public_Transportation       Normal_Weight  
2  Public_Transportation       Normal_Weight  
3                Walking  Overweight_Level_I  
4  Public_Transportation  Overweight_Level_I

In [4]:
datasets.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [5]:
le_ObesityLevel = LabelEncoder()
le_ObesityLevel.fit(datasets['NObeyesdad']) 
data_encoded_ObL = le_ObesityLevel.transform(datasets['NObeyesdad'])
data_encoded_ObL

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,

In [6]:
le_ObesityLevel.classes_

array(['Normal_Weight', 'Overweight_Level_I'], dtype=object)

In [7]:
datasets_1 = datasets.apply(le_ObesityLevel.fit_transform) # for all the attributes
datasets_1

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0         0    7      14      29                               1     0     1   
1         0    7       4      19                               1     0     2   
2         1    9      33      46                               1     0     1   
3         1   14      33      57                               0     0     2   
4         1    8      31      60                               0     0     1   
..      ...  ...     ...     ...                             ...   ...   ...   
494       0    4      19      32                               0     1     2   
495       1    5      33      25                               1     1     2   
496       1    4      25      13                               1     1     1   
497       1    6       8       5                               0     0     1   
498       0   12      21      76                               1     1     2   

     NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0      1     2      0     2    0    0    1     3       3           0  
1      1     2      1     3    1    4    0     2       3           0  
2      1     2      0     2    0    3    1     1       3           0  
3      1     2      0     2    0    3    0     1       4           1  
4      0     2      0     2    0    0    0     2       3           1  
..   ...   ...    ...   ...  ...  ...  ...   ...     ...         ...  
494    1     2      0     2    0    0    0     2       3           0  
495    0     0      0     0    1    0    0     3       2           0  
496    1     2      0     2    0    0    2     2       3           0  
497    1     2      0     2    0    2    1     2       3           0  
498    1     2      0     1    0    1    1     2       3           1  

[499 rows x 17 columns]

In [8]:
X = datasets_1[datasets.columns.drop('NObeyesdad')]
Y = datasets_1['NObeyesdad']

In [9]:
X

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0         0    7      14      29                               1     0     1   
1         0    7       4      19                               1     0     2   
2         1    9      33      46                               1     0     1   
3         1   14      33      57                               0     0     2   
4         1    8      31      60                               0     0     1   
..      ...  ...     ...     ...                             ...   ...   ...   
494       0    4      19      32                               0     1     2   
495       1    5      33      25                               1     1     2   
496       1    4      25      13                               1     1     1   
497       1    6       8       5                               0     0     1   
498       0   12      21      76                               1     1     2   

     NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  
0      1     2      0     2    0    0    1     3       3  
1      1     2      1     3    1    4    0     2       3  
2      1     2      0     2    0    3    1     1       3  
3      1     2      0     2    0    3    0     1       4  
4      0     2      0     2    0    0    0     2       3  
..   ...   ...    ...   ...  ...  ...  ...   ...     ...  
494    1     2      0     2    0    0    0     2       3  
495    0     0      0     0    1    0    0     3       2  
496    1     2      0     2    0    0    2     2       3  
497    1     2      0     2    0    2    1     2       3  
498    1     2      0     1    0    1    1     2       3  

[499 rows x 16 columns]

In [10]:
Y

0      0
1      0
2      0
3      1
4      1
      ..
494    0
495    0
496    0
497    0
498    1
Name: NObeyesdad, Length: 499, dtype: int64

In [11]:
#Decision Tree Classification
dt = DecisionTreeClassifier()
scores = cross_val_score(dt, X, Y, cv=5)
print(scores.mean())

0.9618787878787879


In [12]:
#ADABOOST CLASIFIER

In [14]:
#pentru primul set de parametri
seed = 7
num_trees = 30
kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=seed)

model = AdaBoostClassifier(base_estimator = dt, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)

print(results)
print(results.mean())

#split the dataset: train + test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
model.fit(X_train,Y_train)

#Predict the response for test dataset
Y_prediction = model.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#test the model using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= model.predict(my_tests)
print("Prediction form my given test:",Y_prediction_test)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

[0.92       1.         0.96       1.         0.98       0.96
 0.94       0.98       0.94       0.93877551]
0.9618775510204081
Y_prediction: [1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Prediction form my given test: [0 0 1]
Confusion Matrix:
[[59  1]
 [ 2 38]]
Accuracy score: 0.97
Precision score: 0.9743589743589743
Recall score: 0.95
F1 score: 0.9620253164556962


/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


In [15]:
#pentru al doilea set de parametri
seed = 5
num_trees = 50
kfold = model_selection.KFold(n_splits=10, shuffle=True, random_state=seed)

model = AdaBoostClassifier(base_estimator = dt, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)

print(results)
print(results.mean())

#split the dataset: train + test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)
model.fit(X_train,Y_train)

#Predict the response for test dataset
Y_prediction = model.predict(X_test)
print("Y_prediction:",Y_prediction)
print("Y_test:",Y_test)

#test the model using 3 samples
my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]
Y_prediction_test= model.predict(my_tests)
print("Prediction form my given test:",Y_prediction_test)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))

[0.96       0.92       0.94       0.96       1.         0.96
 0.92       0.98       0.96       0.93877551]
0.953877551020408
Y_prediction: [1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
Y_test: 90     1
254    0
283    0
444    0
474    0
      ..
381    0
56     0
439    0
60     0
208    0
Name: NObeyesdad, Length: 100, dtype: int64
Prediction form my given test: [0 0 1]
Confusion Matrix:
[[59  1]
 [ 3 37]]
Accuracy score: 0.96
Precision score: 0.9736842105263158
Recall score: 0.925
F1 score: 0.9487179487179489


/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(


In [16]:
#GRADIENT BOOSTING

In [18]:
#pentru primul set de parametri
num_trees = 100
kfold = model_selection.KFold(n_splits=10)

model = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

X_for_train, X_for_test, Y_for_train, Y_for_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)

my_test = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]

# Train GradientBoostingClassifier: fitting the X and Y
gboost = GradientBoostingClassifier(n_estimators=100,learning_rate=1)
gboost.fit(X_for_train, Y_for_train)

#Predict the response for test dataset
Y_prediction = gboost.predict(X_test)
# test using the sample given: test the model using 3 new samples, and print the results
Y_prediction_test= gboost.predict(my_test)

#print the predictions
print("Prediction form my given test:",Y_prediction_test)
print("Prediction:",Y_prediction)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))


0.9638775510204081
Prediction form my given test: [0 0 1]
Prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0]
Confusion Matrix:
[[60  0]
 [ 3 37]]
Accuracy score: 0.97
Precision score: 1.0
Recall score: 0.925
F1 score: 0.961038961038961


/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


In [48]:
#pentru al doilea set de parametri
num_trees = 300
kfold = model_selection.KFold(n_splits=10)

model = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

X_for_train, X_for_test, Y_for_train, Y_for_test = train_test_split(X, Y, test_size = 0.15, random_state = 0)

my_tests = [[0,7,14,29,1,0,1,1,2,0,2,0,0,1,3,3],[0,7,4,19,1,0,2,1,2,1,3,1,4,0,2,3],[1,14,33,57,0,0,2,1,2,0,2,0,3,0,1,4]]

# Train GradientBoostingClassifier: fitting the X and Y
gboost = GradientBoostingClassifier(n_estimators=100,learning_rate=1)
gboost.fit(X_for_train, Y_for_train)

#Predict the response for test dataset
Y_prediction = gboost.predict(X_test)
# test using the sample given: test the model using 3 new samples, and print the results
Y_prediction_test= gboost.predict(my_test)

#print the predictions
print("Prediction form my given test:",Y_prediction_test)
print("Prediction:",Y_prediction)

#check/test 5 metrics for classification
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_test, Y_prediction)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_test, Y_prediction))
print("Precision score:",metrics.precision_score(Y_test, Y_prediction))
print("Recall score:",metrics.recall_score(Y_test, Y_prediction))
print("F1 score:",f1_score(Y_test, Y_prediction))


0.9658775510204081
Prediction form my given test: [0 0 1]
Prediction: [1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0]
Confusion Matrix:
[[60  0]
 [ 3 37]]
Accuracy score: 0.97
Precision score: 1.0
Recall score: 0.925
F1 score: 0.961038961038961


/home/izabella/anaconda3/envs/my_env/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
