In [33]:
import os
import subprocess

import pandas as pd
import numpy as np
import graphviz
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn import tree

In [13]:
#citesc setul de date
datasets = pd.read_csv('ObesityDataSet.csv')

In [14]:
#afisez primele 5 
datasets.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no     2   
1  Female  21.0    1.52    56.0                            yes   no     3   
2    Male  23.0    1.80    77.0                            yes   no     2   
3    Male  27.0    1.80    87.0                             no   no     3   
4    Male  22.0    1.78    89.8                             no   no     2   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0    3  Sometimes    no   2.0   no  0.0    1          no   
1    3  Sometimes   yes   3.0  yes  3.0    0   Sometimes   
2    3  Sometimes    no   2.0   no  2.0    1  Frequently   
3    3  Sometimes    no   2.0   no  2.0    0  Frequently   
4    1  Sometimes    no   2.0   no  0.0    0   Sometimes   

                  MTRANS          NObeyesdad  
0  Public_Transportation       Normal_Weight  
1  Public_Transportation       Normal_Weight  
2  Public_Transportation       Normal_Weight  
3                Walking  Overweight_Level_I  
4  Public_Transportation  Overweight_Level_I

In [15]:
datasets.shape

(499, 17)

In [16]:
datasets.dtypes

Gender                             object
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                                int64
NCP                                 int64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                                 int64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [17]:
le_ObesityLevel = LabelEncoder()
le_ObesityLevel.fit(datasets['NObeyesdad']) 
data_encoded_ObL = le_ObesityLevel.transform(datasets['NObeyesdad'])
data_encoded_ObL

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,

In [18]:
le_ObesityLevel.classes_

array(['Normal_Weight', 'Overweight_Level_I'], dtype=object)

In [19]:
datasets_1 = datasets.apply(le_ObesityLevel.fit_transform) # for all the attributes
datasets_1

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0         0    7      14      29                               1     0     1   
1         0    7       4      19                               1     0     2   
2         1    9      33      46                               1     0     1   
3         1   14      33      57                               0     0     2   
4         1    8      31      60                               0     0     1   
..      ...  ...     ...     ...                             ...   ...   ...   
494       0    4      19      32                               0     1     2   
495       1    5      33      25                               1     1     2   
496       1    4      25      13                               1     1     1   
497       1    6       8       5                               0     0     1   
498       0   12      21      76                               1     1     2   

     NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0      1     2      0     2    0    0    1     3       3           0  
1      1     2      1     3    1    4    0     2       3           0  
2      1     2      0     2    0    3    1     1       3           0  
3      1     2      0     2    0    3    0     1       4           1  
4      0     2      0     2    0    0    0     2       3           1  
..   ...   ...    ...   ...  ...  ...  ...   ...     ...         ...  
494    1     2      0     2    0    0    0     2       3           0  
495    0     0      0     0    1    0    0     3       2           0  
496    1     2      0     2    0    0    2     2       3           0  
497    1     2      0     2    0    2    1     2       3           0  
498    1     2      0     1    0    1    1     2       3           1  

[499 rows x 17 columns]

In [20]:
X = datasets_1[datasets.columns.drop('NObeyesdad')]
Y = datasets_1['NObeyesdad']

In [21]:
X

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0         0    7      14      29                               1     0     1   
1         0    7       4      19                               1     0     2   
2         1    9      33      46                               1     0     1   
3         1   14      33      57                               0     0     2   
4         1    8      31      60                               0     0     1   
..      ...  ...     ...     ...                             ...   ...   ...   
494       0    4      19      32                               0     1     2   
495       1    5      33      25                               1     1     2   
496       1    4      25      13                               1     1     1   
497       1    6       8       5                               0     0     1   
498       0   12      21      76                               1     1     2   

     NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  
0      1     2      0     2    0    0    1     3       3  
1      1     2      1     3    1    4    0     2       3  
2      1     2      0     2    0    3    1     1       3  
3      1     2      0     2    0    3    0     1       4  
4      0     2      0     2    0    0    0     2       3  
..   ...   ...    ...   ...  ...  ...  ...   ...     ...  
494    1     2      0     2    0    0    0     2       3  
495    0     0      0     0    1    0    0     3       2  
496    1     2      0     2    0    0    2     2       3  
497    1     2      0     2    0    2    1     2       3  
498    1     2      0     1    0    1    1     2       3  

[499 rows x 16 columns]

In [22]:
Y

0      0
1      0
2      0
3      1
4      1
      ..
494    0
495    0
496    0
497    0
498    1
Name: NObeyesdad, Length: 499, dtype: int64

In [23]:
#Impart dataset-ul in Training set si Test set
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.25)

In [24]:
X_Train

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
64        0    7      18      20                               1     1     1   
353       0   10      12      10                               1     1     0   
45        0    7       5      31                               1     0     1   
238       0    6      14      13                               0     1     2   
363       1    5      33      49                               0     1     1   
..      ...  ...     ...     ...                             ...   ...   ...   
374       1    4      29      39                               1     1     1   
12        1    8      17      19                               0     0     2   
272       1    4      23      25                               0     1     1   
139       1   11      23      36                               0     1     1   
405       1    4      27      56                               0     0     2   

     NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  
64     1     1      0     0    0    2    1     3       3  
353    1     2      0     2    0    0    1     2       0  
45     1     2      0     0    0    0    1     3       3  
238    0     2      0     3    0    2    1     3       3  
363    0     2      0     2    0    3    1     2       3  
..   ...   ...    ...   ...  ...  ...  ...   ...     ...  
374    2     1      0     2    0    3    1     2       0  
12     1     2      0     3    0    3    0     2       3  
272    1     2      0     2    0    3    1     3       3  
139    1     1      0     2    0    0    1     3       3  
405    1     2      0     2    0    4    0     3       3  

[374 rows x 16 columns]

In [25]:
Y_Train

64     0
353    0
45     1
238    0
363    0
      ..
374    0
12     0
272    0
139    0
405    1
Name: NObeyesdad, Length: 374, dtype: int64

In [26]:
print(len(X_Train))
print(len(X_Test))
print(len(Y_Train))
print(len(Y_Test))

374
125
374
125


In [27]:
#Feature Scaling
stdScaler = StandardScaler() #Standardize features by removing the mean and scaling to unit variance
X_Train = stdScaler.fit_transform(X_Train)
X_Test = stdScaler.transform(X_Test)

In [28]:
X_Train

array([[-1.09544512, -0.3555065 , -0.31931143, ...,  0.46143898,
         1.22884788,  0.42618806],
       [-1.09544512,  0.09879679, -0.92809211, ...,  0.46143898,
        -0.38374548, -1.90641195],
       [-1.09544512, -0.3555065 , -1.63833623, ...,  0.46143898,
         1.22884788,  0.42618806],
       ...,
       [ 0.91287093, -0.80980979,  0.1880058 , ...,  0.46143898,
         1.22884788,  0.42618806],
       [ 0.91287093,  0.25023122,  0.1880058 , ...,  0.46143898,
         1.22884788,  0.42618806],
       [ 0.91287093, -0.80980979,  0.59385958, ..., -0.96482696,
         1.22884788,  0.42618806]])

In [29]:
Y_Train

64     0
353    0
45     1
238    0
363    0
      ..
374    0
12     0
272    0
139    0
405    1
Name: NObeyesdad, Length: 374, dtype: int64

In [34]:
dt1 = tree.DecisionTreeClassifier(criterion="entropy")
dt1

DecisionTreeClassifier(criterion='entropy')

In [35]:
dt1.fit(X_Train, Y_Train)

DecisionTreeClassifier(criterion='entropy')

In [36]:
pred = dt1.predict(X_Test)
pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [37]:
dt1.predict_proba(X_Test)

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [38]:
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_Test, pred)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_Test, pred))
print("Precision score:",metrics.precision_score(Y_Test, pred))
print("Recall score:",metrics.recall_score(Y_Test, pred))
print("F1 score:",f1_score(Y_Test, pred))

Confusion Matrix:
[[78  3]
 [ 4 40]]
Accuracy score: 0.944
Precision score: 0.9302325581395349
Recall score: 0.9090909090909091
F1 score: 0.9195402298850575


In [40]:
dt2 = tree.DecisionTreeClassifier(criterion="gini")
dt2

DecisionTreeClassifier()

In [41]:
dt2.fit(X_Train, Y_Train)

DecisionTreeClassifier()

In [42]:
X_Train

array([[-1.09544512, -0.3555065 , -0.31931143, ...,  0.46143898,
         1.22884788,  0.42618806],
       [-1.09544512,  0.09879679, -0.92809211, ...,  0.46143898,
        -0.38374548, -1.90641195],
       [-1.09544512, -0.3555065 , -1.63833623, ...,  0.46143898,
         1.22884788,  0.42618806],
       ...,
       [ 0.91287093, -0.80980979,  0.1880058 , ...,  0.46143898,
         1.22884788,  0.42618806],
       [ 0.91287093,  0.25023122,  0.1880058 , ...,  0.46143898,
         1.22884788,  0.42618806],
       [ 0.91287093, -0.80980979,  0.59385958, ..., -0.96482696,
         1.22884788,  0.42618806]])

In [43]:
Y_Train

64     0
353    0
45     1
238    0
363    0
      ..
374    0
12     0
272    0
139    0
405    1
Name: NObeyesdad, Length: 374, dtype: int64

In [44]:
pred = dt2.predict(X_Test)
pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [45]:
dt2.predict_proba(X_Test)

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [46]:
#METRICA 1: Matricea de confuzie
#METRICA 2: Accuracy;
#METRICA 3: Precision
#METRICA 4: Recall
#METRICA 5: F1
from sklearn import metrics
matrix = confusion_matrix(Y_Test, pred)
print("Confusion Matrix:")
print(matrix)
print("Accuracy score:",metrics.accuracy_score(Y_Test, pred))
print("Precision score:",metrics.precision_score(Y_Test, pred))
print("Recall score:",metrics.recall_score(Y_Test, pred))
print("F1 score:",f1_score(Y_Test, pred))

Confusion Matrix:
[[78  3]
 [ 1 43]]
Accuracy score: 0.968
Precision score: 0.9347826086956522
Recall score: 0.9772727272727273
F1 score: 0.9555555555555557
